# Generated by Django 4.0.2 on 2022-12-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_newcoin_reward_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
