# Generated by Django 4.0.2 on 2023-02-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(default='english', max_length=20),
        ),
    ]
