# Generated by Django 4.0.2 on 2023-04-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='redeemedPremium',
            field=models.BooleanField(default=False),
        ),
    ]
