# Generated by Django 4.0.2 on 2023-04-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_redeemedpremium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_renewal_date',
            field=models.DateField(null=True),
        ),
    ]
