# Generated by Django 4.0.2 on 2023-04-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_premium_renewal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='premium_renewal_date',
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together={('user', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='usertasks',
            unique_together={('user', 'task_number')},
        ),
    ]
