# Generated by Django 4.0.2 on 2023-04-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_premium_renewal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=50),
        ),
    ]
