# Generated by Django 4.0.2 on 2023-04-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_reward_options_alter_user_premium_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fact', 'user')},
            },
        ),
    ]
