# Generated by Django 4.0.2 on 2023-04-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrequest',
            name='response',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
