# Generated by Django 4.0.2 on 2023-05-14 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_analytics_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('closeButton', models.BooleanField(default=False)),
                ('btnOkText', models.CharField(blank=True, max_length=25, null=True)),
                ('btnCancelText', models.CharField(blank=True, max_length=25, null=True)),
                ('isBtnOkLink', models.BooleanField(default=False)),
                ('btnOkLink', models.URLField(blank=True, null=True)),
                ('targetPage', models.CharField(blank=True, choices=[('APP_SETTINGS', 'APP_SETTINGS'), ('ACCOUNT_SETTINGS', 'ACCOUNT_SETTINGS'), ('FONT_SETTINGS', 'FONT_SETTINGS'), ('FONT_SETTINGS', 'FONT_SETTINGS'), ('LANGUAGE_SETTINGS', 'LANGUAGE_SETTINGS'), ('AVATAR_SETTINGS', 'AVATAR_SETTINGS'), ('ACCOUNT_BACKUP', 'ACCOUNT_BACKUP'), ('RATING_POPUP', 'RATING_POPUP'), ('CATEGORY_REQUEST', 'CATEGORY_REQUEST'), ('CATEGORY_REQUEST_STATUS', 'CATEGORY_REQUEST_STATUS'), ('CATEGORY_ADD', 'CATEGORY_ADD'), ('COIN_PAGE', 'COIN_PAGE'), ('SEARCH_PAGE', 'SEARCH_PAGE'), ('DASHBOARD_PAGE', 'DASHBOARD_PAGE'), ('PREMIUM_PAGE', 'PREMIUM_PAGE'), ('CATEGORY_VIEW_ALL', 'CATEGORY_VIEW_ALL')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
