# Generated by Django 4.0.2 on 2023-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_lang_alter_analytics_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isActive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='targetPage',
            field=models.CharField(blank=True, choices=[('APP_SETTINGS', 'APP_SETTINGS'), ('ACCOUNT_SETTINGS', 'ACCOUNT_SETTINGS'), ('FONT_SETTINGS', 'FONT_SETTINGS'), ('LANGUAGE_SETTINGS', 'LANGUAGE_SETTINGS'), ('AVATAR_SETTINGS', 'AVATAR_SETTINGS'), ('ACCOUNT_BACKUP', 'ACCOUNT_BACKUP'), ('RATING_POPUP', 'RATING_POPUP'), ('CATEGORY_REQUEST', 'CATEGORY_REQUEST'), ('CATEGORY_REQUEST_STATUS', 'CATEGORY_REQUEST_STATUS'), ('CATEGORY_ADD', 'CATEGORY_ADD'), ('COIN_PAGE', 'COIN_PAGE'), ('SEARCH_PAGE', 'SEARCH_PAGE'), ('DASHBOARD_PAGE', 'DASHBOARD_PAGE'), ('PREMIUM_PAGE', 'PREMIUM_PAGE'), ('CATEGORY_VIEW_ALL', 'CATEGORY_VIEW_ALL'), ('NAME_UPDATE', 'NAME_UPDATE'), ('PASSWORD_RESET', 'PASSWORD_RESET')], max_length=50, null=True),
        ),
    ]
