# Generated by Django 4.0.2 on 2023-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_category_isactive_alter_appnotification_targetpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
