# Generated by Django 4.0.2 on 2023-05-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_category_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isSpecial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
