# Generated by Django 4.0.2 on 2022-09-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
