# Generated by Django 4.0.2 on 2022-09-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_activity_message_read_alter_message_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='uid',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='uid',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
