# Generated by Django 4.0.2 on 2022-12-11 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_publicmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicmessage',
            name='uid',
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
