# Generated by Django 4.0.2 on 2022-10-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.SmallIntegerField(blank=True, null=True)),
                ('player2', models.SmallIntegerField(blank=True, null=True)),
                ('currentTurn', models.SmallIntegerField(blank=True, null=True)),
                ('currectEmoji', models.CharField(blank=True, max_length=20, null=True)),
                ('guessedEmoji', models.CharField(blank=True, max_length=20, null=True)),
                ('p1score', models.SmallIntegerField(default=0)),
                ('p2score', models.SmallIntegerField(default=0)),
                ('targetScore', models.IntegerField(default=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gameClosed', models.BooleanField(default=False)),
            ],
        ),
    ]
