# Generated by Django 4.0.2 on 2022-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moji_talk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='op1',
            field=models.CharField(default='🎊', max_length=20),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='op2',
            field=models.CharField(default='🙇', max_length=20),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='op3',
            field=models.CharField(default='🐯', max_length=20),
        ),
    ]
