# Generated by Django 4.0.2 on 2023-02-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
