# Generated by Django 4.0.2 on 2023-02-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_bgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgimage',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
